name = "Tapioca Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e49d91327a97632fec46bc797df1e48698ac14a3abc6d438978be119885e10eb"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
