name = "Tapioca Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bd280dda620c4d91bf585d5c53f659c6189ee87584051c988629d55653dbf8d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
