name = "Tapioca Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a5321c127de47d0fcd0f40965ca28918b7fb3173f68cd8b253d061f2fa421dc"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
